### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by oncerist** [Spark-NF/twitter_media_downloader#30]
D:\Downloads\twitter_media_downloader-master>python twitter_media_downloader.py -o out -f "[%date%] %filename%.%ext%" -s large -u Twitter
Resolving: 0 tweets [00:00, ? tweets/s]Traceback (most recent call last):
  File "D:\Downloads\twitter_media_downloader-master\twitter_media_downloader.py", line 38, in <module>
    medias = get_medias(AUTH, user_id, ARGS.retweets, ARGS.image_size, ARGS.since, ARGS.since_id, ARGS.until, ARGS.until_id, ARGS.likes)
  File "D:\Downloads\twitter_media_downloader-master\src\parser.py", line 104, in get_medias
    for tweet in tweepy.Cursor(capi, id=user_id, include_rts=include_retweets, include_entities=True, tweet_mode='extended', since_id=since_id, max_id=until_id).items():
  File "C:\Users\Nowie\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\cursor.py", line 51, in __next__
    return self.next()
  File "C:\Users\Nowie\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\cursor.py", line 243, in next
    self.current_page = self.page_iterator.next()
  File "C:\Users\Nowie\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\cursor.py", line 132, in next
    data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kwargs)
  File "C:\Users\Nowie\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\Nowie\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Twitter error response: status code = 403
Resolving: 0 tweets [00:00, ? tweets/s]

How to fix this?

**Comment by aidenmitchell** [comment]
Same issue here.
```
Resolving: 0 tweets [00:00, ? tweets/s]Traceback (most recent call last):
  File "C:\Users\aiden.admin\Downloads\twitter_media_downloader-master\twitter_media_downloader-master\twitter_media_downloader.py", line 38, in <module>
    medias = get_medias(AUTH, user_id, ARGS.retweets, ARGS.image_size, ARGS.since, ARGS.since_id, ARGS.until, ARGS.until_id, ARGS.likes)
  File "C:\Users\aiden.admin\Downloads\twitter_media_downloader-master\twitter_media_downloader-master\src\parser.py", line 104, in get_medias
    for tweet in tweepy.Cursor(capi, id=user_id, include_rts=include_retweets, include_entities=True, tweet_mode='extended', since_id=since_id, max_id=until_id).items():
  File "C:\Users\aiden.admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tweepy\cursor.py", line 51, in __next__
    return self.next()
  File "C:\Users\aiden.admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tweepy\cursor.py", line 243, in next
    self.current_page = self.page_iterator.next()
  File "C:\Users\aiden.admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tweepy\cursor.py", line 132, in next
    data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kwargs)
  File "C:\Users\aiden.admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\aiden.admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Twitter error response: status code = 403
```

**Comment by Dimen7io** [comment]
Hello i encountered the same issue running 
`C:\Users\MONTEL\twitter_media_downloader>python twitter_media_downloader.py 'username'` ,
I'm using python 3.9.9 on windows 10 on cmd.exe , i used `pip install -r requirements.txt` to have the correct libraries . 
no matter what i search i get the same error message , do you have any idea why ? If you need more information feel free to ask . Thank you .
`Resolving: 0 tweets [00:00, ? tweets/s]Traceback (most recent call last):
  File "C:\Users\MONTEL\twitter_media_downloader\twitter_media_downloader.py", line 38, in <module>
    medias = get_medias(AUTH, user_id, ARGS.retweets, ARGS.image_size, ARGS.since, ARGS.since_id, ARGS.until, ARGS.until_id, ARGS.likes)
  File "C:\Users\MONTEL\twitter_media_downloader\src\parser.py", line 104, in get_medias
    for tweet in tweepy.Cursor(capi, id=user_id, include_rts=include_retweets, include_entities=True, tweet_mode='extended', since_id=since_id, max_id=until_id).items():
  File "C:\Users\MONTEL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tweepy\cursor.py", line 51, in __next__
    return self.next()
  File "C:\Users\MONTEL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tweepy\cursor.py", line 243, in next
    self.current_page = self.page_iterator.next()
  File "C:\Users\MONTEL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tweepy\cursor.py", line 132, in next
    data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kwargs)
  File "C:\Users\MONTEL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\MONTEL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Twitter error response: status code = 403
Resolving: 0 tweets [00:00, ? tweets/s]`

**Comment by Dimen7io** [comment]
I Found the solution according to tweepy you actually need the elevated access for your app you can apply for it in the twitter for dev website . regenerate api keys and recreate your profile after and everything should work . Thank you so much for this amazing tool !

**Comment by IIJlOXOCIIAJl** [comment]
> I Found the solution according to tweepy you actually need the elevated access for your app you can apply for it in the twitter for dev website . regenerate api keys and recreate your profile after and everything should work . Thank you so much for this amazing tool !

Please write instructions for using this script. I'm just not a programmer.
